// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: tx.proto

package contract

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Transaction represents a signed action submitted to the network
// THIS MUST MATCH lib.Transaction EXACTLY for signing
type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageType   string                 `protobuf:"bytes,1,opt,name=message_type,json=messageType,proto3" json:"messageType"` // @gotags: json:"messageType"
	Msg           *anypb.Any             `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Signature     *Signature             `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	CreatedHeight uint64                 `protobuf:"varint,4,opt,name=created_height,json=createdHeight,proto3" json:"createdHeight"` // @gotags: json:"createdHeight"
	Time          uint64                 `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	Fee           uint64                 `protobuf:"varint,6,opt,name=fee,proto3" json:"fee,omitempty"`
	Memo          string                 `protobuf:"bytes,7,opt,name=memo,proto3" json:"memo,omitempty"`
	NetworkId     uint64                 `protobuf:"varint,8,opt,name=network_id,json=networkId,proto3" json:"networkID"` // @gotags: json:"networkID"
	ChainId       uint64                 `protobuf:"varint,9,opt,name=chain_id,json=chainId,proto3" json:"chainID"`       // @gotags: json:"chainID"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *Transaction) GetMsg() *anypb.Any {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Transaction) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Transaction) GetCreatedHeight() uint64 {
	if x != nil {
		return x.CreatedHeight
	}
	return 0
}

func (x *Transaction) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Transaction) GetFee() uint64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *Transaction) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

func (x *Transaction) GetNetworkId() uint64 {
	if x != nil {
		return x.NetworkId
	}
	return 0
}

func (x *Transaction) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

// MessageSend transfers tokens between accounts
type MessageSend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAddress   []byte                 `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"fromAddress"` // @gotags: json:"fromAddress"
	ToAddress     []byte                 `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3" json:"toAddress"`       // @gotags: json:"toAddress"
	Amount        uint64                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageSend) Reset() {
	*x = MessageSend{}
	mi := &file_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSend) ProtoMessage() {}

func (x *MessageSend) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSend.ProtoReflect.Descriptor instead.
func (*MessageSend) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{1}
}

func (x *MessageSend) GetFromAddress() []byte {
	if x != nil {
		return x.FromAddress
	}
	return nil
}

func (x *MessageSend) GetToAddress() []byte {
	if x != nil {
		return x.ToAddress
	}
	return nil
}

func (x *MessageSend) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// FeeParams governs minimum fees
type FeeParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SendFee       uint64                 `protobuf:"varint,1,opt,name=send_fee,json=sendFee,proto3" json:"sendFee"` // @gotags: json:"sendFee"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeeParams) Reset() {
	*x = FeeParams{}
	mi := &file_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeParams) ProtoMessage() {}

func (x *FeeParams) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeParams.ProtoReflect.Descriptor instead.
func (*FeeParams) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{2}
}

func (x *FeeParams) GetSendFee() uint64 {
	if x != nil {
		return x.SendFee
	}
	return 0
}

// Signature holds a BLS12-381 public key and signature
type Signature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"publicKey"` // @gotags: json:"publicKey"
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signature) Reset() {
	*x = Signature{}
	mi := &file_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{3}
}

func (x *Signature) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *Signature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// MessageTokenizeAsset registers a real-world asset on-chain and mints fractions.
// 1.5% of fractions go to the OPEC treasury automatically.
type MessageTokenizeAsset struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OwnerAddress   []byte                 `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"ownerAddress"`        // @gotags: json:"ownerAddress"   20 bytes
	AssetName      string                 `protobuf:"bytes,2,opt,name=asset_name,json=assetName,proto3" json:"assetName"`                 // @gotags: json:"assetName"      1-128 chars
	AssetType      string                 `protobuf:"bytes,3,opt,name=asset_type,json=assetType,proto3" json:"assetType"`                 // @gotags: json:"assetType"      e.g. "real_estate"
	MetadataUri    string                 `protobuf:"bytes,4,opt,name=metadata_uri,json=metadataUri,proto3" json:"metadataURI"`           // @gotags: json:"metadataURI"    off-chain reference
	TotalFractions uint64                 `protobuf:"varint,5,opt,name=total_fractions,json=totalFractions,proto3" json:"totalFractions"` // @gotags: json:"totalFractions" >= 2
	FractionPrice  uint64                 `protobuf:"varint,6,opt,name=fraction_price,json=fractionPrice,proto3" json:"fractionPrice"`    // @gotags: json:"fractionPrice"  price per fraction in uOPEC
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageTokenizeAsset) Reset() {
	*x = MessageTokenizeAsset{}
	mi := &file_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageTokenizeAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageTokenizeAsset) ProtoMessage() {}

func (x *MessageTokenizeAsset) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageTokenizeAsset.ProtoReflect.Descriptor instead.
func (*MessageTokenizeAsset) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{4}
}

func (x *MessageTokenizeAsset) GetOwnerAddress() []byte {
	if x != nil {
		return x.OwnerAddress
	}
	return nil
}

func (x *MessageTokenizeAsset) GetAssetName() string {
	if x != nil {
		return x.AssetName
	}
	return ""
}

func (x *MessageTokenizeAsset) GetAssetType() string {
	if x != nil {
		return x.AssetType
	}
	return ""
}

func (x *MessageTokenizeAsset) GetMetadataUri() string {
	if x != nil {
		return x.MetadataUri
	}
	return ""
}

func (x *MessageTokenizeAsset) GetTotalFractions() uint64 {
	if x != nil {
		return x.TotalFractions
	}
	return 0
}

func (x *MessageTokenizeAsset) GetFractionPrice() uint64 {
	if x != nil {
		return x.FractionPrice
	}
	return 0
}

// MessageBuyFraction purchases fractions from the asset owner.
// Cost = quantity * fraction_price. 1.5% platform fee to treasury.
type MessageBuyFraction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuyerAddress  []byte                 `protobuf:"bytes,1,opt,name=buyer_address,json=buyerAddress,proto3" json:"buyerAddress"` // @gotags: json:"buyerAddress" 20 bytes
	AssetId       uint64                 `protobuf:"varint,2,opt,name=asset_id,json=assetId,proto3" json:"assetId"`               // @gotags: json:"assetId"
	Quantity      uint64                 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity"`                            // @gotags: json:"quantity"     >= 1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageBuyFraction) Reset() {
	*x = MessageBuyFraction{}
	mi := &file_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageBuyFraction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageBuyFraction) ProtoMessage() {}

func (x *MessageBuyFraction) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageBuyFraction.ProtoReflect.Descriptor instead.
func (*MessageBuyFraction) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{5}
}

func (x *MessageBuyFraction) GetBuyerAddress() []byte {
	if x != nil {
		return x.BuyerAddress
	}
	return nil
}

func (x *MessageBuyFraction) GetAssetId() uint64 {
	if x != nil {
		return x.AssetId
	}
	return 0
}

func (x *MessageBuyFraction) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// MessageTransferFraction sends fractions peer-to-peer (secondary market).
type MessageTransferFraction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAddress   []byte                 `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"fromAddress"` // @gotags: json:"fromAddress" 20 bytes
	ToAddress     []byte                 `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3" json:"toAddress"`       // @gotags: json:"toAddress"   20 bytes
	AssetId       uint64                 `protobuf:"varint,3,opt,name=asset_id,json=assetId,proto3" json:"assetId"`            // @gotags: json:"assetId"
	Quantity      uint64                 `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity"`                         // @gotags: json:"quantity"    >= 1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageTransferFraction) Reset() {
	*x = MessageTransferFraction{}
	mi := &file_tx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageTransferFraction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageTransferFraction) ProtoMessage() {}

func (x *MessageTransferFraction) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageTransferFraction.ProtoReflect.Descriptor instead.
func (*MessageTransferFraction) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{6}
}

func (x *MessageTransferFraction) GetFromAddress() []byte {
	if x != nil {
		return x.FromAddress
	}
	return nil
}

func (x *MessageTransferFraction) GetToAddress() []byte {
	if x != nil {
		return x.ToAddress
	}
	return nil
}

func (x *MessageTransferFraction) GetAssetId() uint64 {
	if x != nil {
		return x.AssetId
	}
	return 0
}

func (x *MessageTransferFraction) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// MessageDistributeYield fans yield out to all fraction holders of an asset.
// Caller must be the asset owner. Payout proportional to fractions held.
type MessageDistributeYield struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerAddress  []byte                 `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"ownerAddress"` // @gotags: json:"ownerAddress" 20 bytes
	AssetId       uint64                 `protobuf:"varint,2,opt,name=asset_id,json=assetId,proto3" json:"assetId"`               // @gotags: json:"assetId"
	TotalYield    uint64                 `protobuf:"varint,3,opt,name=total_yield,json=totalYield,proto3" json:"totalYield"`      // @gotags: json:"totalYield"   >= 1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageDistributeYield) Reset() {
	*x = MessageDistributeYield{}
	mi := &file_tx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageDistributeYield) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageDistributeYield) ProtoMessage() {}

func (x *MessageDistributeYield) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageDistributeYield.ProtoReflect.Descriptor instead.
func (*MessageDistributeYield) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{7}
}

func (x *MessageDistributeYield) GetOwnerAddress() []byte {
	if x != nil {
		return x.OwnerAddress
	}
	return nil
}

func (x *MessageDistributeYield) GetAssetId() uint64 {
	if x != nil {
		return x.AssetId
	}
	return 0
}

func (x *MessageDistributeYield) GetTotalYield() uint64 {
	if x != nil {
		return x.TotalYield
	}
	return 0
}

// MessageCastVote submits a DAO governance vote.
// Vote weight = total fractions held across all assets by the voter.
// Each address may only vote once per proposal.
type MessageCastVote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoterAddress  []byte                 `protobuf:"bytes,1,opt,name=voter_address,json=voterAddress,proto3" json:"voterAddress"` // @gotags: json:"voterAddress" 20 bytes
	ProposalId    uint64                 `protobuf:"varint,2,opt,name=proposal_id,json=proposalId,proto3" json:"proposalId"`      // @gotags: json:"proposalId"
	Approve       bool                   `protobuf:"varint,3,opt,name=approve,proto3" json:"approve"`                              // @gotags: json:"approve"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageCastVote) Reset() {
	*x = MessageCastVote{}
	mi := &file_tx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageCastVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageCastVote) ProtoMessage() {}

func (x *MessageCastVote) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageCastVote.ProtoReflect.Descriptor instead.
func (*MessageCastVote) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{8}
}

func (x *MessageCastVote) GetVoterAddress() []byte {
	if x != nil {
		return x.VoterAddress
	}
	return nil
}

func (x *MessageCastVote) GetProposalId() uint64 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

func (x *MessageCastVote) GetApprove() bool {
	if x != nil {
		return x.Approve
	}
	return false
}

// Asset is the on-chain record of a tokenized real-world asset.
type Asset struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerAddress   []byte                 `protobuf:"bytes,2,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	AssetName      string                 `protobuf:"bytes,3,opt,name=asset_name,json=assetName,proto3" json:"asset_name,omitempty"`
	AssetType      string                 `protobuf:"bytes,4,opt,name=asset_type,json=assetType,proto3" json:"asset_type,omitempty"`
	MetadataUri    string                 `protobuf:"bytes,5,opt,name=metadata_uri,json=metadataUri,proto3" json:"metadata_uri,omitempty"`
	TotalFractions uint64                 `protobuf:"varint,6,opt,name=total_fractions,json=totalFractions,proto3" json:"total_fractions,omitempty"`
	FractionPrice  uint64                 `protobuf:"varint,7,opt,name=fraction_price,json=fractionPrice,proto3" json:"fraction_price,omitempty"`
	CreatedHeight  uint64                 `protobuf:"varint,8,opt,name=created_height,json=createdHeight,proto3" json:"created_height,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_tx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{9}
}

func (x *Asset) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Asset) GetOwnerAddress() []byte {
	if x != nil {
		return x.OwnerAddress
	}
	return nil
}

func (x *Asset) GetAssetName() string {
	if x != nil {
		return x.AssetName
	}
	return ""
}

func (x *Asset) GetAssetType() string {
	if x != nil {
		return x.AssetType
	}
	return ""
}

func (x *Asset) GetMetadataUri() string {
	if x != nil {
		return x.MetadataUri
	}
	return ""
}

func (x *Asset) GetTotalFractions() uint64 {
	if x != nil {
		return x.TotalFractions
	}
	return 0
}

func (x *Asset) GetFractionPrice() uint64 {
	if x != nil {
		return x.FractionPrice
	}
	return 0
}

func (x *Asset) GetCreatedHeight() uint64 {
	if x != nil {
		return x.CreatedHeight
	}
	return 0
}

// AssetCounter auto-increments to assign unique asset IDs.
type AssetCounter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint64                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetCounter) Reset() {
	*x = AssetCounter{}
	mi := &file_tx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetCounter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetCounter) ProtoMessage() {}

func (x *AssetCounter) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetCounter.ProtoReflect.Descriptor instead.
func (*AssetCounter) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{10}
}

func (x *AssetCounter) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Holding records how many fractions of one asset a single address holds.
type Holding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HolderAddress []byte                 `protobuf:"bytes,1,opt,name=holder_address,json=holderAddress,proto3" json:"holder_address,omitempty"`
	AssetId       uint64                 `protobuf:"varint,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Quantity      uint64                 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Holding) Reset() {
	*x = Holding{}
	mi := &file_tx_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Holding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Holding) ProtoMessage() {}

func (x *Holding) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Holding.ProtoReflect.Descriptor instead.
func (*Holding) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{11}
}

func (x *Holding) GetHolderAddress() []byte {
	if x != nil {
		return x.HolderAddress
	}
	return nil
}

func (x *Holding) GetAssetId() uint64 {
	if x != nil {
		return x.AssetId
	}
	return 0
}

func (x *Holding) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// AssetHolderIndex lists all holder addresses for one asset (for yield fan-out).
type AssetHolderIndex struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HolderAddresses [][]byte               `protobuf:"bytes,1,rep,name=holder_addresses,json=holderAddresses,proto3" json:"holder_addresses,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AssetHolderIndex) Reset() {
	*x = AssetHolderIndex{}
	mi := &file_tx_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetHolderIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetHolderIndex) ProtoMessage() {}

func (x *AssetHolderIndex) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetHolderIndex.ProtoReflect.Descriptor instead.
func (*AssetHolderIndex) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{12}
}

func (x *AssetHolderIndex) GetHolderAddresses() [][]byte {
	if x != nil {
		return x.HolderAddresses
	}
	return nil
}

// HoldingIndex lists all asset IDs held by one address (for vote weight calc).
type HoldingIndex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetIds      []uint64               `protobuf:"varint,1,rep,packed,name=asset_ids,json=assetIds,proto3" json:"asset_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoldingIndex) Reset() {
	*x = HoldingIndex{}
	mi := &file_tx_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldingIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldingIndex) ProtoMessage() {}

func (x *HoldingIndex) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldingIndex.ProtoReflect.Descriptor instead.
func (*HoldingIndex) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{13}
}

func (x *HoldingIndex) GetAssetIds() []uint64 {
	if x != nil {
		return x.AssetIds
	}
	return nil
}

// Proposal is a DAO governance proposal.
type Proposal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Proposer      []byte                 `protobuf:"bytes,2,opt,name=proposer,proto3" json:"proposer,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	YesVotes      uint64                 `protobuf:"varint,4,opt,name=yes_votes,json=yesVotes,proto3" json:"yes_votes,omitempty"`
	NoVotes       uint64                 `protobuf:"varint,5,opt,name=no_votes,json=noVotes,proto3" json:"no_votes,omitempty"`
	CreatedHeight uint64                 `protobuf:"varint,6,opt,name=created_height,json=createdHeight,proto3" json:"created_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proposal) Reset() {
	*x = Proposal{}
	mi := &file_tx_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proposal) ProtoMessage() {}

func (x *Proposal) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proposal.ProtoReflect.Descriptor instead.
func (*Proposal) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{14}
}

func (x *Proposal) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Proposal) GetProposer() []byte {
	if x != nil {
		return x.Proposer
	}
	return nil
}

func (x *Proposal) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Proposal) GetYesVotes() uint64 {
	if x != nil {
		return x.YesVotes
	}
	return 0
}

func (x *Proposal) GetNoVotes() uint64 {
	if x != nil {
		return x.NoVotes
	}
	return 0
}

func (x *Proposal) GetCreatedHeight() uint64 {
	if x != nil {
		return x.CreatedHeight
	}
	return 0
}

// ProposalCounter auto-increments to assign unique proposal IDs.
type ProposalCounter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint64                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposalCounter) Reset() {
	*x = ProposalCounter{}
	mi := &file_tx_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposalCounter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalCounter) ProtoMessage() {}

func (x *ProposalCounter) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalCounter.ProtoReflect.Descriptor instead.
func (*ProposalCounter) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{15}
}

func (x *ProposalCounter) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// VoteRecord marks that an address has already voted on a proposal.
type VoteRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Voted         bool                   `protobuf:"varint,1,opt,name=voted,proto3" json:"voted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteRecord) Reset() {
	*x = VoteRecord{}
	mi := &file_tx_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteRecord) ProtoMessage() {}

func (x *VoteRecord) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteRecord.ProtoReflect.Descriptor instead.
func (*VoteRecord) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{16}
}

func (x *VoteRecord) GetVoted() bool {
	if x != nil {
		return x.Voted
	}
	return false
}

var File_tx_proto protoreflect.FileDescriptor

const file_tx_proto_rawDesc = "" +
	"\n" +
	"\btx.proto\x12\x05types\x1a\x19google/protobuf/any.proto\"\xa3\x02\n" +
	"\vTransaction\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\tR\vmessageType\x12&\n" +
	"\x03msg\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x03msg\x12.\n" +
	"\tsignature\x18\x03 \x01(\v2\x10.types.SignatureR\tsignature\x12%\n" +
	"\x0ecreated_height\x18\x04 \x01(\x04R\rcreatedHeight\x12\x12\n" +
	"\x04time\x18\x05 \x01(\x04R\x04time\x12\x10\n" +
	"\x03fee\x18\x06 \x01(\x04R\x03fee\x12\x12\n" +
	"\x04memo\x18\a \x01(\tR\x04memo\x12\x1d\n" +
	"\n" +
	"network_id\x18\b \x01(\x04R\tnetworkId\x12\x19\n" +
	"\bchain_id\x18\t \x01(\x04R\achainId\"g\n" +
	"\vMessageSend\x12!\n" +
	"\ffrom_address\x18\x01 \x01(\fR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x02 \x01(\fR\ttoAddress\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\"&\n" +
	"\tFeeParams\x12\x19\n" +
	"\bsend_fee\x18\x01 \x01(\x04R\asendFee\"H\n" +
	"\tSignature\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"\xec\x01\n" +
	"\x14MessageTokenizeAsset\x12#\n" +
	"\rowner_address\x18\x01 \x01(\fR\fownerAddress\x12\x1d\n" +
	"\n" +
	"asset_name\x18\x02 \x01(\tR\tassetName\x12\x1d\n" +
	"\n" +
	"asset_type\x18\x03 \x01(\tR\tassetType\x12!\n" +
	"\fmetadata_uri\x18\x04 \x01(\tR\vmetadataUri\x12'\n" +
	"\x0ftotal_fractions\x18\x05 \x01(\x04R\x0etotalFractions\x12%\n" +
	"\x0efraction_price\x18\x06 \x01(\x04R\rfractionPrice\"p\n" +
	"\x12MessageBuyFraction\x12#\n" +
	"\rbuyer_address\x18\x01 \x01(\fR\fbuyerAddress\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\x04R\aassetId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x04R\bquantity\"\x92\x01\n" +
	"\x17MessageTransferFraction\x12!\n" +
	"\ffrom_address\x18\x01 \x01(\fR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x02 \x01(\fR\ttoAddress\x12\x19\n" +
	"\basset_id\x18\x03 \x01(\x04R\aassetId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x04R\bquantity\"y\n" +
	"\x16MessageDistributeYield\x12#\n" +
	"\rowner_address\x18\x01 \x01(\fR\fownerAddress\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\x04R\aassetId\x12\x1f\n" +
	"\vtotal_yield\x18\x03 \x01(\x04R\n" +
	"totalYield\"q\n" +
	"\x0fMessageCastVote\x12#\n" +
	"\rvoter_address\x18\x01 \x01(\fR\fvoterAddress\x12\x1f\n" +
	"\vproposal_id\x18\x02 \x01(\x04R\n" +
	"proposalId\x12\x18\n" +
	"\aapprove\x18\x03 \x01(\bR\aapprove\"\x94\x02\n" +
	"\x05Asset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12#\n" +
	"\rowner_address\x18\x02 \x01(\fR\fownerAddress\x12\x1d\n" +
	"\n" +
	"asset_name\x18\x03 \x01(\tR\tassetName\x12\x1d\n" +
	"\n" +
	"asset_type\x18\x04 \x01(\tR\tassetType\x12!\n" +
	"\fmetadata_uri\x18\x05 \x01(\tR\vmetadataUri\x12'\n" +
	"\x0ftotal_fractions\x18\x06 \x01(\x04R\x0etotalFractions\x12%\n" +
	"\x0efraction_price\x18\a \x01(\x04R\rfractionPrice\x12%\n" +
	"\x0ecreated_height\x18\b \x01(\x04R\rcreatedHeight\"$\n" +
	"\fAssetCounter\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x04R\x05count\"g\n" +
	"\aHolding\x12%\n" +
	"\x0eholder_address\x18\x01 \x01(\fR\rholderAddress\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\x04R\aassetId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x04R\bquantity\"=\n" +
	"\x10AssetHolderIndex\x12)\n" +
	"\x10holder_addresses\x18\x01 \x03(\fR\x0fholderAddresses\"+\n" +
	"\fHoldingIndex\x12\x1b\n" +
	"\tasset_ids\x18\x01 \x03(\x04R\bassetIds\"\xb7\x01\n" +
	"\bProposal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\bproposer\x18\x02 \x01(\fR\bproposer\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tyes_votes\x18\x04 \x01(\x04R\byesVotes\x12\x19\n" +
	"\bno_votes\x18\x05 \x01(\x04R\anoVotes\x12%\n" +
	"\x0ecreated_height\x18\x06 \x01(\x04R\rcreatedHeight\"'\n" +
	"\x0fProposalCounter\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x04R\x05count\"\"\n" +
	"\n" +
	"VoteRecord\x12\x14\n" +
	"\x05voted\x18\x01 \x01(\bR\x05votedB.Z,github.com/Dremo15/canopy/plugin/go/contractb\x06proto3"

var (
	file_tx_proto_rawDescOnce sync.Once
	file_tx_proto_rawDescData []byte
)

func file_tx_proto_rawDescGZIP() []byte {
	file_tx_proto_rawDescOnce.Do(func() {
		file_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tx_proto_rawDesc), len(file_tx_proto_rawDesc)))
	})
	return file_tx_proto_rawDescData
}

var file_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_tx_proto_goTypes = []any{
	(*Transaction)(nil),             // 0: types.Transaction
	(*MessageSend)(nil),             // 1: types.MessageSend
	(*FeeParams)(nil),               // 2: types.FeeParams
	(*Signature)(nil),               // 3: types.Signature
	(*MessageTokenizeAsset)(nil),    // 4: types.MessageTokenizeAsset
	(*MessageBuyFraction)(nil),      // 5: types.MessageBuyFraction
	(*MessageTransferFraction)(nil), // 6: types.MessageTransferFraction
	(*MessageDistributeYield)(nil),  // 7: types.MessageDistributeYield
	(*MessageCastVote)(nil),         // 8: types.MessageCastVote
	(*Asset)(nil),                   // 9: types.Asset
	(*AssetCounter)(nil),            // 10: types.AssetCounter
	(*Holding)(nil),                 // 11: types.Holding
	(*AssetHolderIndex)(nil),        // 12: types.AssetHolderIndex
	(*HoldingIndex)(nil),            // 13: types.HoldingIndex
	(*Proposal)(nil),                // 14: types.Proposal
	(*ProposalCounter)(nil),         // 15: types.ProposalCounter
	(*VoteRecord)(nil),              // 16: types.VoteRecord
	(*anypb.Any)(nil),               // 17: google.protobuf.Any
}
var file_tx_proto_depIdxs = []int32{
	17, // 0: types.Transaction.msg:type_name -> google.protobuf.Any
	3,  // 1: types.Transaction.signature:type_name -> types.Signature
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_tx_proto_init() }
func file_tx_proto_init() {
	if File_tx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tx_proto_rawDesc), len(file_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tx_proto_goTypes,
		DependencyIndexes: file_tx_proto_depIdxs,
		MessageInfos:      file_tx_proto_msgTypes,
	}.Build()
	File_tx_proto = out.File
	file_tx_proto_goTypes = nil
	file_tx_proto_depIdxs = nil
}
